# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots

# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's
# enough to test only against the last release in a major GHC
# version. Feel free to omit lines listings versions you don't
# need/want testing for.
env:
 - GHCVER=7.6.3
 - GHCVER=7.8.3
 - GHCVER=head  # see section about GHC HEAD snapshots

# This should allow passing even when there are problems with GHC head MB
matrix:
  allow_failures:
   - env: GHCVER=head


# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install bc cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - ls /opt/ghc/$GHCVER/bin

install:
 - cabal-1.18 update
 # This is a hack to make Travis happy because it doesn't install happy/alex by default
 - cabal-1.18 install happy alex

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - export CABAL=cabal-1.18
 - export JENKINS_GHC=$GHCVER
 - ./.jenkins_script.sh

 # - cabal-1.18 configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 # - cabal-1.18 build   # this builds all libraries and executables (including tests/benchmarks)
 # - cabal-1.18 test
 # - cabal-1.18 check
 # - cabal-1.18 sdist   # tests that a source-distribution can be generated
